config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post '/login', to: 'auth#login', default: {:format => :json}
  post '/signup', to: 'auth#signup', default: {:format => :json}
  post '/logout', to: 'auth#logout', default: {:format => :json}

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show]
  end

  resources :posts, only: %i[new create destroy] do
    resources :comments, only: %i[new create destroy]
    resources :likes, only: %i[create destroy]
  end

  # Defines the root path route ("/")
  root "users#index"
  
  scope 'api' do
    get '/posts/:id/comments' => 'api/comments#index', as: :api_post_comments
    post '/posts/:id/comments' => 'api/comments#create', as: :api_post_comments_create
    resources :users, only: [] do
      get '/posts' => 'api/posts#index', as: :api_user_posts
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :trackable
  has_many :posts, class_name: 'Post', foreign_key: 'user_id', inverse_of: :user, dependent: :destroy
  has_many :comments, class_name: 'Comment', foreign_key: 'user_id', inverse_of: :user, dependent: :destroy
  has_many :likes, class_name: 'Like', foreign_key: 'user_id', inverse_of: :user, dependent: :destroy

  validates :name, presence: true
  validates :bio, presence: true
  validates :photo, presence: true
  validates :posts_counter, presence: true, numericality: { only_integer: true },
                            comparison: { greater_than_or_equal_to: 0 }

  after_initialize :default_values

  def most_recent_posts(items = 3)
    posts.order(created_at: :desc).take(items)
  end

  def posts_desc_order
    posts.order(created_at: :desc)
  end

  def generate_jwt
    JWT.encode({ id:,
                 exp: 60.days.from_now.to_i },
               Rails.application.secrets.secret_key_base)
  end

  private

  def default_values
    return unless new_record?

    self.photo ||= 'user_photo.png'
    self.posts_counter ||= 0
    self.role ||= 'default'
    self.bio ||= 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'
  end

  def authenticate(password)
    valid_password?(password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(id: :asc)
    @current_user = current_user
  end

  def show
    @current_user = current_user
    @user = User.find(params[:id])
  end
end

app/views/users/_post.html.erb
<li>
  <h4><%= post.title %></h4>

  <p><%= post.text %></p>

  <div>
    <button type="button">
      Comments:
      <span>
        <%= post.comments_counter  ? post.comments_counter : 0 %>
      </span>
    </button>
    <button type="button">
      Likes:
      <span>
        <%= post.likes_counter ? post.likes_counter  : 0 %>
      </span>
    </button>
  </div>
</li>

app/views/users/_user.html.erb
<li>

  <a href="/users/<%= user.id %>">
    <%= content_tag(:div, tag.img(src: user.photo, alt: "#{user.name}'s photo", width: '150px'), class: 'card') %>
  </a>

  <h2><%= user.name %></h2>

  <button type="button">
    Number of posts:
    <span>
      <%= user.posts_counter ? user.posts_counter : 0 %>
    </span>
  </button>

</li>

app/views/users/_user_card.html.erb
<div>
  <div>
    <%= image_tag user.photo, alt: "#{user.name}'s photo", :style => "width: 100px;" %>
  </div>
  <div>
    <%= tag.h1(user.name) %>
    <p>Number of posts: <%= tag.span(user.posts_counter) %></p>
  </div>
  <%= link_to '', user_path(user.id), id: "link_user-#{user.id}" %>
</div>

app/views/users/index.html.erb
<%= render partial: 'user_card', collection: @users, as: :user %>

app/views/users/show.html.erb
<%= content_tag(:div, content_tag(:a, 'Edit Profile', href: edit_user_registration_path)) %>
<%= render 'user_card', user: @user %>
<%= content_tag(:div, tag.p(@current_user.bio), class: 'card__box') %>
<%= render partial: 'posts/post_card', collection: @current_user.most_recent_posts, as: :post, locals: { detailed: false } %>
<%= link_to 'See all posts', user_posts_path(@current_user.id) %>