config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post '/login', to: 'auth#login', default: {:format => :json}
  post '/signup', to: 'auth#signup', default: {:format => :json}
  post '/logout', to: 'auth#logout', default: {:format => :json}

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show]
  end

  resources :posts, only: %i[new create destroy] do
    resources :comments, only: %i[new create destroy]
    resources :likes, only: %i[create destroy]
  end

  # Defines the root path route ("/")
  root "users#index"
  
  scope 'api' do
    get '/posts/:id/comments' => 'api/comments#index', as: :api_post_comments
    post '/posts/:id/comments' => 'api/comments#create', as: :api_post_comments_create
    resources :users, only: [] do
      get '/posts' => 'api/posts#index', as: :api_user_posts
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id', inverse_of: :posts
  has_many :comments, class_name: 'Comment', foreign_key: 'post_id', inverse_of: :post, dependent: :destroy
  has_many :likes, class_name: 'Like', foreign_key: 'post_id', inverse_of: :post, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :text, presence: true
  validates :comments_counter, presence: true, numericality: { only_integer: true },
                               comparison: { greater_than_or_equal_to: 0 }
  validates :likes_counter, presence: true, numericality: { only_integer: true },
                            comparison: { greater_than_or_equal_to: 0 }

  after_create :increment_posts_counter
  after_destroy :decrement_posts_counter

  def most_recent_comments(items = 5)
    comments.order(created_at: :desc).take(items)
  end

  private

  def increment_posts_counter
    user.increment!(:posts_counter)
  end

  def decrement_posts_counter
    user.decrement!(:posts_counter)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  before_action :require_login

  def index
    posts = Post.where(user_id: params[:user_id]).order(created_at: :desc)
    render json: { posts: }, status: :ok
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @current_user = current_user
    @user = User.find(params[:user_id])
    @posts_and_comments = @user.posts_desc_order.includes(:comments)
  end

  def show
    @current_user = current_user
    @post = Post.find(params[:id])
  end

  def new
    @current_user = current_user
  end

  def create
    @current_user = current_user
    @post = @current_user.posts.new(post_params)
    @post.comments_counter = 0
    @post.likes_counter = 0
    if @post.save
      flash[:success] = 'Post saved successfully'
      redirect_to user_posts_url(@current_user.id)
    else
      flash.now[:error] = @post.errors.full_messages.to_sentence
      render :new, locals: { user: @current_user }, status: 422
    end
  end

  def destroy
    @post = Post.find(params[:post][:post_id])
    post_user_id = @post.user.id
    @post.destroy
    redirect_to user_url(post_user_id)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/_add_comment.html.erb
<%= form_with(model: [ post.user, post.user.comments.build ], url: "/users/#{post.user.id}/posts/#{post.id}/comments") do |form| %>

  <div>
    <%= form.text_field :text, placeholder:"Add a comment" %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/posts/_add_like.html.erb
<%= form_with url: "/users/#{post.user.id}/posts/#{post.id}/likes" do |form| %>
  <%= form.submit "Like" %>
    <span>
      <%= post.likes_counter ? post.likes_counter  : 0 %>
    </span>
<% end %>

app/views/posts/_form.html.erb
<%= form_with model: post do |form| %>

    <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |message| %>
      <div class="alert alert-danger" role="alert">
        <%= message %> S
      </div>
    <% end %>       
  <% end %>

    <div>
    <% form.label :title %>
    <%= form.text_field :title, class:"form-control", placeholder:" Title of the post" %>
  </div>

  <div>
    <%= form.text_field :text, class:"form-control", placeholder:"Content of the post" %>
  </div>

  <div>
    <%= form.submit class:'btn btn-primary' %>
  </div>
  
<% end %>

app/views/posts/_post.html.erb
<li>

  <a href="/users/<%= @user.id %>/posts/<%= post.id %>">
    <div>
      <h4><%= post.title %></h4>

      <p><%= post.text %></p>

      <div>
        <button type="button">
          Comments:
          <span>
            <%= post.comments_counter  ? post.comments_counter : 0 %>
          </span>
        </button>
        <button type="button" disable>
          Likes:
          <span>
            <%= post.likes_counter ? post.likes_counter  : 0 %>
          </span>
        </button>
      </div>

      <h4> Comments </h4>
  
      <ul>
        <% if post.comments.length > 0 %>
          <% post.comments.each do |comment| %>
          <li><%= comment.user.name %> : <%= comment.text %></li>
          <% end %>
        <% else %>
          <li>No comments</li>
        <% end %>
      </ul>
      
    </div>
  </a>
</li>

app/views/posts/_post_card.html.erb
<div>
<%= link_to tag.h2(post.title, class: 'card__title'), user_post_path(post.user.id, post.id), class: 'link' %>
  <%= content_tag(:div, post.text, class: ['card__text', ('truncated-text' unless detailed)]) %>
  <div class="card__counters <%= 'card__counters-detailed' if detailed %>">
    <div class="counter__comments">
      <%= button_to 'Comments: ', new_post_comment_path(post.id), method: :get %>
      <%= tag.span(post.comments_counter) %>
    </div>
   <div class="counter__likes">
      <% like = @current_user.likes.find_by(post: post) %>
      <% if like.nil? %>
        <%= button_to 'Likes:', post_likes_path(post.id), params: { like: { post_id: post.id }}, method: :post %>
      <% else %>
        <%= button_to 'Unlike:', post_like_path(post.id, like.id), params: { like: { post_id: post.id, like_id: like.id }} , method: :delete %>
      <% end %>
      <%= tag.span(post.likes_counter) %>
    </div>
    <% if can? :destroy, post %>
    <div class="owner__admin">
      <%= button_to 'Delete', post_path(post.id), params: { post: { post_id: post.id} }, method: :delete %>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<%= render 'users/user_card', user: @user %>
<%= render 'layouts/alert', flash: flash %>
<% @posts_and_comments.each do |post| %>
  <% if post.comments_counter > 0 %>
    <div>
  <% end %>
  <%= render 'post_card', post: post, detailed: false %>
  <% if post.comments_counter > 0 %>
    <div>
      <%= render partial: 'comments/comment_card', collection: post.comments.first(5), as: :comment %>
    </div>
    </div>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<div class="container">
<%= tag.h1('New Post', class: 'form__title') %>
<%= render 'layouts/alert', flash: flash %>
<%= form_with model: Post.new do |f| %>


<div class="form__container">
<%= tag.h1('New Post', class: 'form__title') %>
<%= render 'layouts/alert', flash: flash %>
<%= form_with model: Post.new do |f| %>
  <%= f.text_field :title, placeholder: 'Title' %>
  <%= f.text_area :text, rows: 20, placeholder: 'Enter the content' %>
  <%= f.submit 'Save' %>
</div>
<% end %>
<% end %>
</div>

app/views/posts/show.html.erb
<%= render 'layouts/alert', flash: flash %>
<%= render 'post_card', post: @post, detailed: true %>
<% if @post.comments_counter > 0 %>
  <div class="card__box">
    <%= tag.h3('Comments:', class: 'card__title') %>
    <%= render partial: 'comments/comment_card', collection: @post.comments, as: :comment %>
  </div>
<% end %>